### PR TITLE
D2IQ-64547: uses typography components in ConfigMap

### PR DESCRIPTION
**Pull request by mperrotti**
These changes also include some spacing adjustments.

## Screenshots
Before:
Screen Shot 2020-02-28 at 6 17 54 PM

After:
Screen Shot 2020-02-28 at 6 18 07 PM

### CODE REVIEW

**Comment by GeorgiSTodorov** [comment]
I cannot get custom tags for `ConfigurationMapHeading` working.
Peek 2020-03-02 12-32

**Comment by mperrotti** [comment]
@GeorgiSTodorov - should be fixed now

**Comment by brandonc** [comment]
Can we get a smoke test in DCOS? @Poltergeist

**Comment by mperrotti** [comment]
@brandonc we don't use ui-kit ConfigurationMap components in DC/OS yet.

**Comment by GeorgiSTodorov** [comment]
@mperrotti , there are conflicting files.

**Pull request merged**
