### PR TITLE
Add Commitizen config

### PR DESCRIPTION
**Pull request by Poltergeist**
<details><summary><strong>chore(package.json): add commitizen config</strong></summary><hr/>

This adds the conventional changelog config for commitizen.
[commitizen](https://github.com/commitizen/cz-cli)
</details>

---
Commit:
07ef6ee904ed849b1cd75f38c0338bd44055af59

### CODE REVIEW

**Comment by weblancaster** [comment]
I feel this is unnecessary, the project is also unmaintained so I don't like the idea of having a lot of node_modules unmaintained, because in the long term we need to keep the packages up to date.

**Comment by ahoskins** [comment]
I recently changed in dcos-ui to use: `@commitlint/config-conventional` https://github.com/dcos/dcos-ui/blob/master/package.json#L77...it makes sense that this repo and dcos-ui would use the same tooling for linting/changelog. No strong opinions either way, just consistency.

**Comment by juliangieseke** [comment]
```
"@commitlint/cli": "6.1.3",
"@commitlint/config-conventional": "6.1.3",
```
its in here already 👍  the tool added by philipp is only about generating commit messages (and i _really_ like this tool, want to have it in dcos-ui also 👍 
@Poltergeist can you please add a short gif/video of how it works? I'm alsmost sure that the guys are instantly sold after seeing it :)

**Comment by DanielMSchmidt** [comment]
@juliangieseke Thank you for explaining, I understood it differently 🙈

**Comment by Poltergeist** [comment]
commitizen mov
I hope this explains more what it does. I think this is adding value because it will generate commits based on a style definition.

**Pull request merged**
