### PR TITLE
DCOS-40966: added components to handle toast notifications

### PR DESCRIPTION
**Pull request by mperrotti**
This should work as-is, but we can probably follow-up to make `Toaster` stateless by storing `toasts` data in the datalayer and adding GraphQL mutations for adding and removing toasts

## Screenshots:
toastdismissorder

### CODE REVIEW

**Comment by mperrotti** [comment]
To do in the morning before we can merge:
- Better typing of a few things
- More stories in Storybook
- Better Toaster test coverage

There's still plenty to review though, so have at it :)

**Comment by mperrotti** [comment]
@GeorgiSTodorov - here's a clearer screenshot. They get removed in the order they get added

toastdemo

**Comment by mperrotti** [comment]
@GeorgiSTodorov - here's a clearer screenshot. They get removed in the order they get added. You can play with it in the third story, "autodissmiss"

toastdismissorder

**Comment by mperrotti** [comment]
@GeorgiSTodorov - you're right, I'll update the story

**Comment by GeorgiSTodorov** [comment]
Failing tests:
screenshot from 2018-10-15 12-39-45

**Comment by GeorgiSTodorov** [comment]
One solution I found was:
```
    expect(instance.state.toasts && instance.state.toasts.length).toEqual(1);
    instance.componentWillReceiveProps(newProps);
    expect(instance.state.toasts && instance.state.toasts.length).toEqual(2);
```

**Comment by GeorgiSTodorov** [comment]
I still see the old code in "Files changed": https://github.com/dcos-labs/ui-kit/pull/234/files#diff-f1aabe6e41806b467901bd2f36d7acc1R73

**Pull request merged**
