### PR TITLE
DCOS-46337: resizable table columns

### PR DESCRIPTION
**Pull request by mperrotti**
Table columns can be resized by setting the `resize` prop on the respective `Column`

TableResizeDemo_04092018

### CODE REVIEW

**Comment by mperrotti** [comment]
Hold merge until design gives their final signoff

**Comment by mperrotti** [comment]
@GeorgiSTodorov - I added a maximum width a column can be resized. I set it so no column can take up more than 80% of the table container's width.

**Comment by GeorgiSTodorov** [comment]
I broke it again.
Peek 2019-04-05 17-23

**Comment by mperrotti** [comment]
Clever, @GeorgiSTodorov. Were you a QA engineer in a past life? :p

I'll try and guard against that scenario, but I don't know if that's a realistic state a user would ever get to.

**Comment by GeorgiSTodorov** [comment]
@mperrotti , can we set a maximum width for the table?

**Comment by mperrotti** [comment]
I don't understand why we'd do that. Tables should be able to be as wide as they need to be.
I pushed up a fix I'm pretty sure you won't be able to break this time ;)

**Comment by GeorgiSTodorov** [comment]
Does this count?
Peek 2019-04-05 20-51

**Comment by mperrotti** [comment]
@GeorgiSTodorov - Your thorough testing never ceases to amaze me :)

**Comment by mperrotti** [comment]
Reviewed with design today. Two things left to decide on:
- Visual design of the resize handle
- Whether resizing is opt-in or opt-out (use a `noResize` prop instead of `resizable`?)

**Comment by AmrAbdelrazik** [comment]
@mperrotti are we getting double click to resize & fit content?
@izharbuendia may I suggest opt-out please forgetting to block sizing of a column is less important than forgetting to enable sizing on an important column (it would be very annoying)

**Comment by mperrotti** [comment]
@AmrAbdelrazik 
We are not getting double-click to resize and fit content in this PR. I tried implementing it, and it hurt performance when scrolling and hovering in a DC/OS soak cluster

**Comment by GeorgiSTodorov** [comment]
This might be an edge case.

**Comment by mperrotti** [comment]
@GeorgiSTodorov - that's very edge case-y. I feel confident users won't get themselves into that situation.

**Comment by mperrotti** [comment]
@natmegs and @GeorgiSTodorov - please re-review. I made visual design updates to the resize handle requested by the design team, and moved the `onResize` prop from Table to Column because it seemed like a better component API

**Pull request merged**
