### PR TITLE
[spike] Replace values duplicated by design tokens

### PR DESCRIPTION
**Pull request by mperrotti**
https://jira.mesosphere.com/browse/DCOS-46024

### CODE REVIEW

**Comment by mperrotti** [comment]
This shouldn't merge without https://github.com/dcos-labs/ui-kit/pull/260 - it will break flexItem gutters, which have been fixed in that PR

**Comment by GeorgiSTodorov** [comment]
Conflicts, because I merged https://github.com/dcos-labs/ui-kit/pull/260 .

**Comment by mperrotti** [comment]
I think this is unrelated to these changes, but definitely something I'll fix. Thanks for catching!

**Comment by mperrotti** [comment]
That error appears to be coming from `action` (from `@storybook/addon-actions`), and it only happens in Firefox. Also, the function is still called successfully.

I don't think this is something we have to worry about fixing - it doesn't happen if I pass in my own function

**Comment by GeorgiSTodorov** [comment]
File conflicts.

**Pull request merged**
