### PR TITLE
Rename React methods

### PR DESCRIPTION
**Pull request by GeorgiSTodorov**
Everything should still work the same way as before.

### CODE REVIEW

**Comment by brandonc** [comment]
I also did this before I saw it was an open PR #460 but mine converts one of these to componentDidUpdate since it appears to be be a side effect

**Comment by GeorgiSTodorov** [comment]
Thanks for letting me know, @brandonc . I will take a look tomorrow.

**Comment by mperrotti** [comment]
@GeorgiSTodorov - can we close this and just use https://github.com/dcos-labs/ui-kit/pull/460?

**Comment by GeorgiSTodorov** [comment]
@mperrotti , that's fine with me.

**Pull request closed without merging**
