### PR TITLE
DCOS-40018: janky row alignment when user scrolls very fast

### PR DESCRIPTION
**Pull request by mperrotti**
This is caused by a known issue with MultiGrid. [This issue comment](https://github.com/bvaughn/react-virtualized/issues/291#issuecomment-234766955) helped me come to a solution

## Screenshots:
Red background added to better demonstrate the jank

Before:
scrolljank_before

After:
scrolljank_after

## Testing
1. In `Table.stories.tsx`, add a bunch of mock data to the `items` array
2. (optional) Add ```[css`background-color: red;`]: rowIndex % 2 > 0``` to the class name rendered in the div returned by the `getContentCell` method
3. Go to the default Table story and scroll up and down in the table as fast as you can

The rows should not appear to vertically misalign as you scroll

I was not able to get a local branch of ui-kit linked in `dcos-ui` to test these changes on the nodes page using a soak cluster, but I'm working on it.

### CODE REVIEW

**Comment by weblancaster** [comment]
@mperrotti this is AWESOME!

**Comment by GeorgiSTodorov** [comment]
For me it still looks weird.

peek 2018-08-22 16-14

**Comment by mperrotti** [comment]
Thanks @GeorgiSTodorov, I'm able to reproduce in Firefox (using Firefox Quantum 61.0.2) on macOS.

One weird thing to note:
The problem doesn't happen when I have Firefox's DevTools open

**Comment by jaxesn** [comment]
Woah smart! I'd timebox your investigation into Firefox and if you can't readily fix it, I'd still ship to fix chrome esp since it is by far our top used browser.

**Comment by mperrotti** [comment]
I spent a little more time trying to get this working in Firefox too, but no success :/

Just going to merge once I get one more approval

**Comment by rufusraghunath** [comment]
Hey everyone, I'm obviously super late to the party, but I'm very curious about this changeset. How do @mperrotti's changes produce the desired effect?

Also, I'm currently using `react-virtualized@9.21.0` and it seems the fix is no longer working out of the box? I had to add the same styles to the container element of my `Grid` for them to take effect.

**Pull request merged**
