### PR TITLE
fix: kill bottom margin on CheckboxInput in dcos-ui

### PR DESCRIPTION
**Pull request by mperrotti**
CNVS adds a bottom margin to `label`s using a style with high specificity, which is causing the checkbox in CheckboxTable to look misaligned.

Before:
Screen Shot 2019-03-14 at 10 58 16 PM

After:
Screen Shot 2019-03-14 at 10 59 09 PM

### CODE REVIEW

**Comment by GeorgiSTodorov** [comment]
File conflict.

**Comment by GeorgiSTodorov** [comment]
Rebased.

**Comment by GeorgiSTodorov** [comment]
The failing tests are passing locally.

**Comment by GeorgiSTodorov** [comment]
Okay, the failing tests are also failing on master.

**Comment by GeorgiSTodorov** [comment]
@mperrotti , I notice to difference between master and this PR. I tested in both Firefox and Chrome.
### Here
Screenshot from 2019-08-16 08-58-51

### master
Screenshot from 2019-08-16 09-00-39

Also, related to the recent tooltip PR that we merged, when I hover the checkbox for the first row, it says "Toggle row 0".
Screenshot from 2019-08-16 09-04-38

**Comment by mperrotti** [comment]
@GeorgiSTodorov - there wouldn't be a visible difference in ui-kit. These changes override CNVS styles in DC/OS

**Comment by GeorgiSTodorov** [comment]
@mperrotti , it's not a blocker.

**Pull request merged**
