### PR TITLE
fix: snapshots

### PR DESCRIPTION
**Pull request by taksuparth**
# Description
- Fix ci which is failing for snapshot test of `pagniation.test.tsx`

## Checklist

- [ ] If any new components were added, there are exported from `packages/index.ts`
- [ ] This PR is associated with a JIRA and mentions in the commit message footer ("Closes …")
- [ ] This PR contains breaking changes and states in the commit message body ("BREAKING CHANGE: …")
- [x] I have reviewed the changes and provided detail to the sections above

### CODE REVIEW

**Comment by taksuparth** [comment]
@nataliepina please check this. CI is failing in the main branch after the merge of TextInput PR

**Comment by nataliepina** [comment]
Could you refactor the commit message to be `test:` instead of `fix:`
- **Tests**
  `test` - Adding missing tests or correcting existing tests.
  
Will need to make sure to always run ` npm run test -- -u` but CI should have caught this 🤔

**Comment by taksuparth** [comment]
No, @nataliepina no need to always run test cases with update flag. 

Why did this happen?: 

PR-1 had changes related to Paginaton tests

PR-2 had changes related to hidden attribute

Both were in review together. Pipelines for both got succeded. Now PR-1 got merged but its test will break with PR-2 changes. Since it's ci alredy successfully passed, it did not get retriggered and got merged in main. Hence, now main branch is in a state where ci is breaking.

This is very common ci issue.

**Comment by nataliepina** [comment]
Thanks for the input @taksuparth. Either way, this should be good after you refactor the commit type.

**Comment by vacas5** [comment]
thanks for doing this but since it was blocking other PRs we got it in separately

**Pull request closed without merging**
