### PR TITLE
Check Storybook components for console errors / warnings

### PR DESCRIPTION
**Pull request by DanielMSchmidt**
CI should be read because AppChrome has a key error / warning

### CODE REVIEW

**Comment by mperrotti** [comment]
@DanielMSchmidt - can we change this PR to not run Cypress on commit? It makes commits take forever :/

**Comment by DanielMSchmidt** [comment]
@mperrotti I changed it, now we just need to make the PR ready by fixing the issue that explodes currently (or skip the test) ;)

**Comment by mperrotti** [comment]
@DanielMSchmidt - Cypress appears to error before it even runs the tests:
```

[20:39:57]  Verifying Cypress can run /root/.cache/Cypress/3.4.0/Cypress [started]

[20:39:57]  Verifying Cypress can run /root/.cache/Cypress/3.4.0/Cypress [failed]

Your system is missing the dependency: Xvfb



Install Xvfb and run Cypress again.



Read our documentation on dependencies for more information:



https://on.cypress.io/required-dependencies



If you are using Docker, we provide containers with all required dependencies installed.



----------



Error: spawn Xvfb ENOENT



----------



Platform: linux (Raspbian - )

Cypress Version: 3.4.0

npm ERR! code ELIFECYCLE

npm ERR! errno 1

npm ERR! @dcos/ui-kit@0.0.0-dev test:integration: `cypress run`

npm ERR! Exit status 1

npm ERR! 

npm ERR! Failed at the @dcos/ui-kit@0.0.0-dev test:integration script.

npm ERR! This is probably not a problem with npm. There is likely additional logging output above.



npm ERR! A complete log of this run can be found in:

npm ERR!     /root/.npm/_logs/2019-08-01T20_39_57_278Z-debug.log

script returned exit code 1
```

Have you seen this before? I found a thread about this in Cypress' Github issues: https://github.com/cypress-io/cypress-docker-images/issues/39. I'm not sure what needs to be done to fix it

**Comment by DanielMSchmidt** [comment]
Please take a look at the kommander docker image for CI, we would need the
same things that are installed there 🙈

Mike Perrotti <notifications@github.com> schrieb am Do., 1. Aug. 2019,
22:49:

**Comment by mperrotti** [comment]
```
./scripts/test-integration: line 14: lsof: command not found
```
🤦‍♂ whyyy?

**Comment by DanielMSchmidt** [comment]
@mperrotti I moved from getting the pid via the port to just remembering the pid. This workaround does not work in the other project due to restart scripts, but for storybook it's sufficient 👍 (I hope at least :D )

**Pull request merged**
