### PR TITLE
Add "support" icon

### PR DESCRIPTION
**Pull request by mperrotti**
## Screenshot (outdated, see comments)
Screen Shot 2019-07-10 at 4 18 21 PM

### CODE REVIEW

**Comment by mperrotti** [comment]
@danielone and @izharbuendia :
The icon I added doesn't match the style of the other icons. How would you feel about using this version instead?

Screen Shot 2019-07-10 at 4 22 17 PM

**Comment by GeorgiSTodorov** [comment]
I can't see this icon in the system icons.

**Comment by mperrotti** [comment]
@GeorgiSTodorov - you might have to run `npm run build:svg` first

**Comment by danielone** [comment]
Yes this icon we did pull from the new set for Protoss (which was never merged)

+1

**Comment by mperrotti** [comment]
Updated the icon with Daniel's blessing

**Pull request merged**
