### PR TITLE
chore(deps): update dependency npm to v6

### PR DESCRIPTION
**Pull request by mesosphere-web**
This Pull Request updates dependency [npm](https://github.com/npm/npm) from `v5.8.0` to `v6.0.1`

<details>
<summary>Release Notes</summary>

### [`v6.0.1`](https://github.com/npm/npm/releases/v6.0.1)
[Compare Source](https://github.com/npm/npm/compare/v6.0.1-next.0...v6.0.1)
##### CTRL-C OUT DURING PACKAGE EXTRACTION AS MUCH AS YOU WANT!

* [`b267bbbb9`](https://github.com/npm/npm/commit/b267bbbb9ddd551e3dbd162cc2597be041b9382c) [npm/lockfile#&#8203;29](`https://github.com/npm/lockfile/pull/29`) `lockfile@&#8203;1.0.4`: Switches to `signal-exit` to detect abnormal exits and remove locks. ([@&#8203;Redsandro])
##### SHRONKWRAPS AND LACKFILES

If a published modules had legacy `npm-shrinkwrap.json` we were saving ordinary registry dependencies (`name@&#8203;version`) to your `package-lock.json` as `https://` URLs instead of versions.

* [`89102c0d9`](https://github.com/npm/npm/commit/89102c0d995c3d707ff2b56995a97a1610f8b532) When saving the lock-file compute how the dependency is being required instead of using `_resolved` in the `package.json`. This fixes the bug that was converting registry dependencies into `https://` dependencies. ([@&#8203;iarna])
* [`676f1239a`](https://github.com/npm/npm/commit/676f1239ab337ff967741895dbe3a6b6349467b6) When encountering a `https://` URL in our lockfiles that point at our default registry, extract the version and use them as registry dependencies. This lets us heal `package-lock.json` files produced by 6.0.0 ([@&#8203;iarna])
##### AUDIT AUDIT EVERYWHERE

You can't use it _quite_ yet, but we do have a few last moment patches to `npm audit` to make it even better when it is turned on!

* [`b2e4f48f5`](https://github.com/npm/npm/commit/b2e4f48f5c07b8ebc94a46ce01a810dd5d6cd20c) Make sure we hide stream errors on background audit submissions. Previously some classes of error could end up being displayed (harmlessly) during installs. ([@&#8203;iarna])
* [`1fe0c7fea`](https://github.com/npm/npm/commit/1fe0c7fea226e592c96b8ab22fd9435e200420e9) Include session and scope in requests (as we do in other requests to the registry). ([@&#8203;iarna])
* [`d04656461`](https://github.com/npm/npm/commit/d046564614639c37e7984fff127c79a8ddcc0c92) Exit with non-zero status when vulnerabilities are found. So you can have `npm audit` as a test or prepublish step! ([@&#8203;iarna])
* [`fcdbcbacc`](https://github.com/npm/npm/commit/fcdbcbacc16d96a8696dde4b6d7c1cba77828337) Verify lockfile integrity before running. You'd get an error either way, but this way it's faster and can give you more concrete instructions on how to fix it. ([@&#8203;iarna])
* [`2ac8edd42`](https://github.com/npm/npm/commit/2ac8edd4248f2393b35896f0300b530e7666bb0e) Refuse to run in global mode. Audits require a lockfile and globals don't have one. Yet. ([@&#8203;iarna])
* [`3dcc240db`](https://github.com/npm/npm/commit/3dcc240dba5258532990534f1bd8a25d1698b0bf) Timeout audit requests eventually. ([@&#8203;iarna])
##### Looking forward

We're still a way from having node@&#8203;11, so now's a good time to ensure we don't warn about being used with it.

* [`ed1aebf55`](https://github.com/npm/npm/commit/ed1aebf55) Allow node@&#8203;11, when it comes. ([@&#8203;iarna])
##### DOCUMENTATION IMPROVEMENTS

* [`b7fca1084`](https://github.com/npm/npm/commit/b7fca1084b0be6f8b87ec0807c6daf91dbc3060a) [#&#8203;20407](`https://github.com/npm/npm/pull/20407`) Update the lock-file spec doc to mention that we now generate the from field for `git`-type dependencies. ([@&#8203;watilde])
* [`7a6555e61`](https://github.com/npm/npm/commit/7a6555e618e4b8459609b7847a9e17de2d4fa36e) [#&#8203;20408](`https://github.com/npm/npm/pull/20408`) Describe what the colors in outdated mean. ([@&#8203;teameh])
##### DEPENDENCY UPDATES

* [`5e56b3209`](https://github.com/npm/npm/commit/5e56b3209c4719e3c4d7f0d9346dfca3881a5d34) `npm-audit-report@&#8203;1.0.8` ([@&#8203;evilpacket])
* [`58a0b31b4`](https://github.com/npm/npm/commit/58a0b31b43245692b4de0f1e798fcaf71f8b7c31) `lock-verify@&#8203;2.0.2` ([@&#8203;iarna])
* [`e7a8c364f`](https://github.com/npm/npm/commit/e7a8c364f3146ffb94357d8dd7f643e5563e2f2b) [zkat/pacote#&#8203;148](`https://github.com/zkat/pacote/pull/148`) `pacote@&#8203;8.1.1` ([@&#8203;redonkulus])
* [`46c0090a5`](https://github.com/npm/npm/commit/46c0090a517526dfec9b1b6483ff640227f0cd10) `tar@&#8203;4.4.2` ([@&#8203;isaacs])
* [`8a16db3e3`](https://github.com/npm/npm/commit/8a16db3e39715301fd085a8f4c80ae836f0ec714) `update-notifier@&#8203;2.5.0` ([@&#8203;alexccl])
* [`696375903`](https://github.com/npm/npm/commit/6963759032fe955c1404d362e14f458d633c9444) `safe-buffer@&#8203;5.1.2` ([@&#8203;feross])
* [`c949eb26a`](https://github.com/npm/npm/commit/c949eb26ab6c0f307e75a546f342bb2ec0403dcf) `query-string@&#8203;6.1.0` ([@&#8203;sindresorhus])

---

### [`v6.0.0`](https://github.com/npm/npm/blob/master/CHANGELOG.md#v600-2018-04-20)
[Compare Source](https://github.com/npm/npm/compare/v6.0.0-next.2...v6.0.0)
Hey y'all! Here's another `npm@&#8203;6` release -- with `node@&#8203;10` around the corner,
this might well be the last prerelease before we tag `6.0.0`! There's two major
features included with this release, along with a few miscellaneous fixes and
changes.
##### EXTENDED `npm init` SCAFFOLDING

Thanks to the wonderful efforts of [@&#8203;jdalton] of
lodash fame, `npm init` can now be used to invoke custom scaffolding tools!

You can now do things like `npm init react-app` or `npm init esm` to scaffold an
npm package by running `create-react-app` and `create-esm`, respectively. This
also adds an `npm create` alias, to correspond to Yarn's `yarn create` feature,
which inspired this.

* [`008a83642`](https://github.com/npm/npm/commit/008a83642e04360e461f56da74b5557d5248a726) [`ed81d1426`](https://github.com/npm/npm/commit/ed81d1426776bcac47492cabef43f65e1d4ab536) [`833046e45`](https://github.com/npm/npm/commit/833046e45fe25f75daffd55caf25599a9f98c148)
  [#&#8203;20303](`https://github.com/npm/npm/pull/20303`)
  Add an `npm init` feature that calls out to `npx` when invoked with positional
  arguments.  ([@&#8203;jdalton])
##### DEPENDENCY AUDITING

This version of npm adds a new command, `npm audit`, which will run a security
audit of your project's dependency tree and notify you about any actions you may
need to take.

The registry-side services required for this command to work will be available
on the main npm registry in the coming weeks. Until then, you won't get much out
of trying to use this on the CLI.

As part of this change, the npm CLI now sends scrubbed and cryptographically
anonymized metadata about your dependency tree to your configured registry, to
allow notifying you about the existence of critical security flaws. For details
about how the CLI protects your privacy when it shares this metadata, see `npm
help audit`, or [read the docs for `npm audit`
online](https://github.com/npm/npm/blob/release-next/doc/cli/npm-audit.md). You
can disable this altogether by doing `npm config set audit false`, but will no
longer benefit from the service.

* [`f4bc648ea`](https://github.com/npm/npm/commit/f4bc648ea7b19d63cc9878c9da2cb1312f6ce152)
  [#&#8203;20389](`https://github.com/npm/npm/pull/20389`)
  `npm-registry-fetch@&#8203;1.1.0`
  ([@&#8203;iarna])
* [`594d16987`](https://github.com/npm/npm/commit/594d16987465014d573c51a49bba6886cc19f8e8)
  [#&#8203;20389](`https://github.com/npm/npm/pull/20389`)
  `npm-audit-report@&#8203;1.0.5`
  ([@&#8203;iarna])
* [`8c77dde74`](https://github.com/npm/npm/commit/8c77dde74a9d8f9007667cd1732c3329e0d52617) [`1d8ac2492`](https://github.com/npm/npm/commit/1d8ac2492196c4752b2e41b23d5ddc92780aaa24) [`552ff6d64`](https://github.com/npm/npm/commit/552ff6d64a5e3bcecb33b2a861c49a3396adad6d) [`09c734803`](https://github.com/npm/npm/commit/09c73480329e75e44fb8e55ca522f798be68d448)
  [#&#8203;20389](`https://github.com/npm/npm/pull/20389`)
  Add new `npm audit` command.
  ([@&#8203;iarna])
* [`be393a290`](https://github.com/npm/npm/commit/be393a290a5207dc75d3d70a32973afb3322306c)
  [#&#8203;20389](`https://github.com/npm/npm/pull/20389`)
  Temporarily suppress git metadata till there's an opt-in.
  ([@&#8203;iarna])
* [`8e713344f`](https://github.com/npm/npm/commit/8e713344f6e0828ddfb7733df20d75e95a5382d8)
  [#&#8203;20389](`https://github.com/npm/npm/pull/20389`)
  Document the new command.
  ([@&#8203;iarna])
*
  [#&#8203;20389](`https://github.com/npm/npm/pull/20389`)
  Default audit to off when running the npm test suite itself.
  ([@&#8203;iarna])
##### MORE `package-lock.json` FORMAT CHANGES?!

* [`820f74ae2`](https://github.com/npm/npm/commit/820f74ae22b7feb875232d46901cc34e9ba995d6)
  [#&#8203;20384](`https://github.com/npm/npm/pull/20384`)
  Add `from` field back into package-lock for git dependencies. This will give
  npm the information it needs to figure out whether git deps are valid,
  specially when running with legacy install metadata or in
  `--package-lock-only` mode when there's no `node_modules`. This should help
  remove a significant amount of git-related churn on the lock-file.
  ([@&#8203;zkat])
##### BUGFIXES

* [`9d5d0a18a`](https://github.com/npm/npm/commit/9d5d0a18a5458655275056156b5aa001140ae4d7)
  [#&#8203;20358](`https://github.com/npm/npm/pull/20358`)
  `npm install-test` (aka `npm it`) will no longer generate `package-lock.json`
  when running with `--no-package-lock` or `package-lock=false`.
  ([@&#8203;raymondfeng])
* [`e4ed976e2`](https://github.com/npm/npm/commit/e4ed976e20b7d1114c920a9dc9faf351f89a31c9)
  [`2facb35fb`](https://github.com/npm/npm/commit/2facb35fbfbbc415e693d350b67413a66ff96204)
  [`9c1eb945b`](https://github.com/npm/npm/commit/9c1eb945be566e24cbbbf186b0437bdec4be53fc)
  [#&#8203;20390](`https://github.com/npm/npm/pull/20390`)
  Fix a scenario where a git dependency had a comittish associated with it
  that was not a complete commitid.  `npm` would never consider that entry
  in the `package.json` as matching the entry in the `package-lock.json` and
  this resulted in inappropriate pruning or reinstallation of git
  dependencies.  This has been addressed in two ways, first, the addition of the
  `from` field as described in [#&#8203;20384](`https://github.com/npm/npm/pull/20384`) means
  we can exactly match the `package.json`. Second, when that's missing (when working with
  older `package-lock.json` files), we assume that the match is ok.  (If
  it's not, we'll fix it up when a real installation is done.)
  ([@&#8203;iarna])
##### DEPENDENCIES

* [`1c1f89b73`](https://github.com/npm/npm/commit/1c1f89b7319b2eef6adee2530c4619ac1c0d83cf)
  `libnpx@&#8203;10.2.0`
  ([@&#8203;zkat])
* [`242d8a647`](https://github.com/npm/npm/commit/242d8a6478b725778c00be8ba3dc85f367006a61)
  `pacote@&#8203;8.1.0`
  ([@&#8203;zkat])
##### DOCS

* [`a1c77d614`](https://github.com/npm/npm/commit/a1c77d614adb4fe6769631b646b817fd490d239c)
  [#&#8203;20331](`https://github.com/npm/npm/pull/20331`)
  Fix broken link to 'private-modules' page. The redirect went away when the new
  npm website went up, but the new URL is better anyway.
  ([@&#8203;vipranarayan14])
* [`ad7a5962d`](https://github.com/npm/npm/commit/ad7a5962d758efcbcfbd9fda9a3d8b38ddbf89a1)
  [#&#8203;20279](`https://github.com/npm/npm/pull/20279`)
  Document the `--if-present` option for `npm run-script`.
  ([@&#8203;aleclarson])

---

</details>

---

This PR has been generated by [Renovate Bot](https://renovatebot.com).

### CODE REVIEW

**Comment by Poltergeist** [comment]
Apparently, we just have to make the jump :-/ It does make sense, we also want to add npm 6 as an engine then. Will do that.

**Comment by Poltergeist** [comment]
The thing is if we don't do this we will end up with multiple different versions of the package-lock file.
Since the way the package-lock is created is different with `npm` 6.

**Comment by DanielMSchmidt** [comment]
But with pinning npm to a specific version the different package-lock should be identical from then on, right? We don't have npm5 and npm6 package locks overwriting each other.

**Comment by Poltergeist** [comment]
For the first install it is using what ever you have local or global so you need to run install twice and then the package-lock.json is consistent.

**Pull request merged**
