### PR TITLE
D2IQ-66047 - Storybook Upgrade

### PR DESCRIPTION
**Pull request by TattdCodeMonkey**
Updated from v5.0 Storybook to v5.3 Storybook.

Major Changes:
- migrated to new configuration files, main.js, preview.js & manager.js
- updated storybook-readme configuration from v4 to v5
- migrated off `addon-options`

Reviewing commit by commit should make it easier since some have lots of the same small changes to most story files.

## Testing

- CI & General regression of storybook 

## Trade-offs

- stories have not be converted to either CSF or MDX yet
- `addon-info` is still being used, instead of being migrated to `addon-docs`
- Both of the above are required to upgrade to Storybook v6

## Checklist for PR creator

- [ ] If any new components were added, there are exported from `packages/index.ts`
- [X] If this PR is associated with a JIRA, it is mentioned in commit message footer ("Closes …")
- [ ] If this PR contains breaking changes, is stated in commit message body ("BREAKING CHANGE: …")
- [ ] Info for applicable sections above is provided

### CODE REVIEW

**Review by natmegs — DISMISSED** [review]
🎉 🎉 
There's an integration test failure for the avatar component but those stories looked fine to me?

**Comment by TattdCodeMonkey** [comment]
@natmegs yea I meant to come back to this and investigate that test, but I forgot 🤦

**Comment by TattdCodeMonkey** [comment]
the integration test failure is legit and its cause  by  a storybook  bug that causes addon tabs to not be rendered in the correct order. which was not fixed in v5 :(  working on a  fix to the test now.

**Review by natmegs — APPROVED** [review]

**Review by brandonc — APPROVED** [review]
Works!

**Pull request merged**
