### PR TITLE
DCOS-43353: add style utility layout components

### PR DESCRIPTION
**Pull request by mperrotti**
These are the style utility components that help us with achieving common layout patterns.

These components are:
Container
Flex
FlexItem
GridList

See the READMEs in this PR for more info

Many of these stories make use of Storybook's "Knobs" panel

## Screenshots
Screen Shot 2019-07-04 at 1 11 38 AM

Screen Shot 2019-07-04 at 1 11 54 AM

Screen Shot 2019-07-04 at 1 12 23 AM

Screen Shot 2019-07-04 at 1 12 57 AM

### CODE REVIEW

**Comment by GeorgiSTodorov** [comment]
24 snapshots are failing.

**Comment by GeorgiSTodorov** [comment]
Flex on column reverse looks a little weird.
Screenshot from 2019-07-04 10-26-51

On Flex > justify, I think the text needs to be changed.
Screenshot from 2019-07-04 10-29-27

On GridList > columnCount, when I delete the value in the knobs or if I enter something other than a number, it breaks.
Screenshot from 2019-07-04 10-32-34

Other than that, it looks great.

**Comment by GeorgiSTodorov** [comment]
The last point of my previous comment is still valid, but I consider it non-blocking. Do we want to merge this PR?

**Comment by pierrebeitz** [comment]
i added some syntactic and type trickery (revealing some inexect types) and fixed the issue @GeorgiSTodorov 	is seeing.

if you don't like it, feel free to remove that commit.

**Comment by mperrotti** [comment]
Merge-able as soon as https://github.com/dcos-labs/ui-kit/pull/358 merges

**Comment by GeorgiSTodorov** [comment]
The build is broken.
```
ERROR in ./packages/styleUtils/layout/container/stories/Container.stories.tsx
Module not found: Error: Can't resolve '../index' in '/home/georgi/dcos/ui-kit/packages/styleUtils/layout/container/stories'
 @ ./packages/styleUtils/layout/container/stories/Container.stories.tsx 17:14-33
 @ ./packages sync .stories.tsx$
 @ ./.storybook/config.js
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/config.js (webpack)-hot-middleware/client.js?reload=true

ERROR in ./packages/styleUtils/layout/gridList/stories/GridList.stories.tsx
Module not found: Error: Can't resolve '../index' in '/home/georgi/dcos/ui-kit/packages/styleUtils/layout/gridList/stories'
 @ ./packages/styleUtils/layout/gridList/stories/GridList.stories.tsx 22:14-33
 @ ./packages sync .stories.tsx$
 @ ./.storybook/config.js
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/config.js (webpack)-hot-middleware/client.js?reload=true
```

**Comment by GeorgiSTodorov** [comment]
In Flex > justify > stretch, they aren't stretched.
Screenshot from 2019-07-09 10-49-08

**Pull request merged**
