### PR TITLE
DCOS-54215: port Tooltip from reactjs-components

### PR DESCRIPTION
**Pull request by mperrotti**
This moves the legacy Tooltip component over from reactjs-components.
Once we port all components reactjs-components to ui-kit, dcos-ui can import legacy components from ui-kit and drop reactjs-components as a dependency.

### In dcos-ui:
1. In ui-kit, run `npm run dist`
2. Replace `dcos-ui/node_modules/@dcos/ui-kit/dist/packages/` with `ui-kit/dist/packages/`
3. Find a place in `dcos-ui` that uses a Tooltip imported from `reactjs-components` and replace the import with
```
import { Legacy } from "@dcos/ui-kit";
```
4. Replace `<Tooltip />` components with `<Legacy.Tooltip />`
5. Start dcos-ui

Check that `<Legacy.Tooltip />` looks and behaves like the `<Tooltip>` from reactjs-components

### In Storybook (optional):
1. Import legacy components to a `*.stories.tsx` file:
```
import { Legacy } from "@dcos/ui-kit";
```
2. Add a story that uses the legacy tooltip (`<Legacy.Tooltip />`)
3. `npm start` and navigate to the story in Storybook

## Screenshot
Switching tabs between a dcos-ui build that is using `Legacy.Tooltip` from ui-kit, and one the daily cluster:
LegacyTooltipDemo

### CODE REVIEW

**Comment by GeorgiSTodorov** [comment]
@mperrotti , I encountered a problem on the third step.
I get this:
Screenshot from 2019-05-23 10-47-14

And when I check the file, I get this:
Screenshot from 2019-05-23 10-48-03

Shouldn't we export Legacy, not Tooltip? Or maybe I am doing something incorrectly.

**Comment by GeorgiSTodorov** [comment]
I got this error in dcos-ui, I think it's because dcos-ui is still on version 2.0.1 in there, so it doesn't have the needed dependencies.
Screenshot from 2019-05-23 11-09-16

I fixed it by first updating ui-kit to a newer version (I used 3.2.0).

**Comment by mperrotti** [comment]
@Poltergeist - could you update your review per our conversation earlier today? :)

**Comment by mperrotti** [comment]
Sorry @GeorgiSTodorov - you're right about the dependency issue.

I was able to import using ```import { Legacy } from "@dcos/ui-kit";```. Did that not work for you?

**Comment by GeorgiSTodorov** [comment]
@mperrotti , I mean about exporting it here, in the ui-kit.

**Pull request merged**
