### PR TITLE
DCOS-43353: add style utility modifier components

### PR DESCRIPTION
**Pull request by mperrotti**
These are the most basic style utility components to give access to simple things like adding a border or applying spacing.

These components are:
Box
SpacingBox
BorderedBox

See the README in this PR for more info

Many of these stories make use of Storybook's "Knobs" panel

## Screenshots
Screen Shot 2019-07-04 at 12 54 06 AM

Screen Shot 2019-07-04 at 12 55 05 AM

Screen Shot 2019-07-04 at 12 53 42 AM

### CODE REVIEW

**Comment by GeorgiSTodorov** [comment]
A test is failing locally as well as in CI.
Screenshot from 2019-07-04 10-05-57

**Comment by GeorgiSTodorov** [comment]
BorderedBox > radius doesn't seem to change for me. Other than that, it looks good.

**Comment by mperrotti** [comment]
@GeorgiSTodorov - that's strange, I'm not getting that error locally. I'll push up what I have locally and see if that fixes it 🤷‍♂

**Comment by GeorgiSTodorov** [comment]
@mperrotti , it's still failing.

**Comment by mperrotti** [comment]
@GeorgiSTodorov as soon as https://github.com/dcos-labs/ui-kit/pull/358 merges

**Comment by pierrebeitz** [comment]
rebased, changed target branch and removed basework-commit.

**Pull request merged**
